version: '3'
services:
  jenkins:
    container_name: jenkins
    image: ansible
    build:
      context: ansible
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

networks:
jenkins-net:

