version: '3'
services:
  jenkins:
    container_name: jenkins
    image: ansible
    build:
      context: ansible
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: ./ubuntu
    networks:
      - jenkins-net

  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - $PWD/db_date:/var/lib/mysql
    networks:
      - jenkins-net

networks:
  jenkins-net:
